  - name: Base
    label: Entity Base
    obj: entity
    attributes:
      - name: name
        label: Entity Name
      - name: tagline
        label: Short description

  - name: Person
    label: Person
    obj: entity
    attributes:
      - name: first_name
        label: First Name
      - name: last_name
        label: Last Name