"""drop crop coordinates

Revision ID: 5830e85b1afe
Revises: 5c5d246934d
Create Date: 2014-07-18 11:07:10.269313

"""

# revision identifiers, used by Alembic.
revision = '5830e85b1afe'
down_revision = '5c5d246934d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grano_imageconfig', 'crop_origin_y')
    op.drop_column('grano_imageconfig', 'crop_origin_x')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grano_imageconfig', sa.Column('crop_origin_x', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grano_imageconfig', sa.Column('crop_origin_y', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
